export let API_URI="http://localhost:3000"
export let LOGINUSER="LOGINUSER"
export let SIGNUPUSER="SIGNUPUSER"
export let GETPRODUCTS="GETPRODUCTS"
export let ISLOGGEDIN="ISLOGGEDIN"
export let VERIFYTOKEN="VERIFYTOKEN"
export let TOKEN="grabittoken"